### ISSUE TITLE
画像保存できません

### ISSUE THREAD

**Issue by PC-BREAKER** [8th713/cockpit-for-pixiv#15]
ショートカット「D」で画像が保存できると思うのですが、「サーバーに問題が発生しました。」と表示されて失敗してしまいます。私の環境が悪いのでしょう？他は特に問題もなく…

**Comment by 8th713** [comment]
現在うごイラ以外の画像の保存は正しく動作しません。
仕様の制限により対応が難しい状況です。

**Comment by PC-BREAKER** [comment]
了解です。
