### ISSUE TITLE
セレクタの変更に弱すぎ問題

### ISSUE THREAD

**Issue by 8th713** [8th713/cockpit-for-pixiv#39]
**問題点**:
pixiv は styled-components や css modules を使っているので CSS セレクタが頻繁に変更される。CSS セレクタが変更されると起動トリガーとなるサムネイルリンクが検出できなくなる。

**望ましい動作**:
pixiv の CSS セレクタが変更されてもサムネイルリンクが検出できる。

**解決策**:
* リンク先が個別イラストページ(/member_illust.php?mode=medium&illust_id=xxx)のアンカータグがターゲットなので属性セレクタ`a[href*="member_illust.php?mode=medium&illust_id="]`を使う。
* ただしこの方法はテキストリンクも拾ってしまうため何らかの手段でテキストリンクを除外する必要がある。
* ターゲットをマウスオーバーしたときカーソルを変更する必要があるためテキストリンクの除外も CSS セレクタで表現しなければならない。
* 上記要求を満たすにはどうしても pixiv の CSS セレクタに依存する必要がありすると変更に弱くなる。
* ただしターゲット検出漏れ(つまり動作しない)よりも除外漏れ(つまり余計な場所でも動作してしまう)のほうがエンドユーザーには優しいので検討の価値がある。

**Comment by hogewest** [comment]
CSSセレクタに依存しない方法を検討してみました #40 

すでに方向性が決まっている場合や、
CSSセレクタとは別に依存してしまっている所がありますし、方向性として問題ある場合は閉じてもらって問題ありません。

CSSセレクタのみでは難しいためJavaScript側で動的に処理する方向にしてみました。

**Comment by 8th713** [comment]
@hogewest ありがとうございます。見た感じ良さそうです。

ただ React 16.8.0 stable がリリースされたので v3 は更新停止して v4 が正式版になります。
v4 はコードベースがまるっきり違うため PR は close になってしまいます。
v4 内で同じ解決法で実装を行いリリースログに @hogewest さんの Contribute であることを注記する形にします。

**Comment by 8th713** [comment]
commit: f493bc58fd16b97721edc00a3d90809cfb99ef6a
